// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CommunitiesPublic = {
    data: Array<CommunityPublic>;
    count: number;
};

export type CommunityCreate = {
    name: string;
    description?: (string | null);
};

export type CommunityPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_by: string;
};

export type CommunityUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SearchResults = {
    users: Array<UserPublic>;
    items: Array<ItemPublic>;
    communities: Array<CommunityPublic>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    password: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    public_id: string;
    id: string;
    communities?: Array<CommunityPublic>;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CommunitiesReadCommunitiesData = {
    limit?: number;
    skip?: number;
};

export type CommunitiesReadCommunitiesResponse = (CommunitiesPublic);

export type CommunitiesCreateCommunityData = {
    requestBody: CommunityCreate;
};

export type CommunitiesCreateCommunityResponse = (CommunityPublic);

export type CommunitiesReadCommunityData = {
    id: string;
};

export type CommunitiesReadCommunityResponse = (CommunityPublic);

export type CommunitiesUpdateCommunityData = {
    id: string;
    requestBody: CommunityUpdate;
};

export type CommunitiesUpdateCommunityResponse = (CommunityPublic);

export type CommunitiesDeleteCommunityData = {
    id: string;
};

export type CommunitiesDeleteCommunityResponse = (Message);

export type CommunitiesJoinCommunityData = {
    id: string;
};

export type CommunitiesJoinCommunityResponse = (Message);

export type CommunitiesLeaveCommunityData = {
    id: string;
    userId?: (string | null);
};

export type CommunitiesLeaveCommunityResponse = (Message);

export type CommunitiesReadCommunityMembersData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type CommunitiesReadCommunityMembersResponse = (UsersPublic);

export type FriendsReadFriendsData = {
    limit?: number;
    skip?: number;
};

export type FriendsReadFriendsResponse = (UsersPublic);

export type FriendsReadFriendRequestsData = {
    limit?: number;
    skip?: number;
};

export type FriendsReadFriendRequestsResponse = (UsersPublic);

export type FriendsCreateFriendRequestData = {
    friendId: string;
};

export type FriendsCreateFriendRequestResponse = (Message);

export type FriendsAcceptFriendRequestData = {
    friendId: string;
};

export type FriendsAcceptFriendRequestResponse = (Message);

export type FriendsRemoveFriendData = {
    friendId: string;
};

export type FriendsRemoveFriendResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SearchSearchData = {
    limit?: number;
    q: string;
};

export type SearchSearchResponse = (SearchResults);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);