// This file is auto-generated by @hey-api/openapi-ts

export type Body_items_create_item = {
    title: string;
    description?: (string | null);
    item_type?: string;
    extra_data?: (string | null);
    image?: ((Blob | File) | null);
    image_url?: (string | null);
};

export type Body_items_update_item = {
    title?: (string | null);
    description?: (string | null);
    item_type?: (string | null);
    extra_data?: (string | null);
    image?: ((Blob | File) | null);
    image_url?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_storage_upload = {
    file: (Blob | File);
};

export type Body_users_upload_user_profile_picture = {
    file: (Blob | File);
};

export type CollectionCreate = {
    title: string;
    description?: (string | null);
    collection_type?: CollectionType;
};

export type CollectionPublic = {
    title: string;
    description?: (string | null);
    collection_type?: CollectionType;
    id: string;
    owner_id: string;
    items?: Array<ItemPublic>;
};

export type CollectionsPublic = {
    data: Array<CollectionPublic>;
    count: number;
};

export type CollectionType = 'general' | 'library';

export type CollectionUpdate = {
    title?: (string | null);
    description?: (string | null);
    collection_type?: (CollectionType | null);
};

export type CommunitiesPublic = {
    data: Array<CommunityPublic>;
    count: number;
};

export type CommunityAnnouncementCreate = {
    title: string;
    content: string;
};

export type CommunityAnnouncementPublic = {
    title: string;
    content: string;
    id: string;
    community_id: string;
    author_id: string;
    created_at: string;
    author: UserPublic;
};

export type CommunityAnnouncementsPublic = {
    data: Array<CommunityAnnouncementPublic>;
    count: number;
};

export type CommunityCreate = {
    name: string;
    description?: (string | null);
    is_closed?: boolean;
};

export type CommunityMemberRole = 'admin' | 'member';

export type CommunityMemberStatus = 'pending' | 'accepted' | 'rejected';

export type CommunityMemberUpdate = {
    role?: (CommunityMemberRole | null);
    status?: (CommunityMemberStatus | null);
};

export type CommunityMessageCreate = {
    content: string;
};

export type CommunityMessagePublic = {
    content: string;
    id: string;
    community_id: string;
    author_id: string;
    created_at: string;
    author: UserPublic;
};

export type CommunityMessagesPublic = {
    data: Array<CommunityMessagePublic>;
    count: number;
};

export type CommunityPublic = {
    name: string;
    description?: (string | null);
    is_closed?: boolean;
    id: string;
    created_by: string;
    current_user_role?: (CommunityMemberRole | null);
};

export type CommunityUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_closed?: (boolean | null);
};

export type FriendshipStatus = 'pending' | 'accepted';

export type GoogleToken = {
    token: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InterestPublic = {
    id: string;
    name: string;
    category: (string | null);
};

export type ItemOwnerPublic = {
    id: string;
    full_name: (string | null);
    email: string;
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    author?: (string | null);
    item_type?: ItemType;
    image_url?: (string | null);
    extra_data?: {
        [key: string]: unknown;
    };
    id: string;
    count: number;
    created_at: string;
    owners?: Array<ItemOwnerPublic>;
    collection_id?: (string | null);
    is_available?: boolean;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemType = 'general' | 'book';

export type LoanCreate = {
    item_id: string;
    start_date: string;
    end_date: string;
};

export type LoanPublic = {
    id: string;
    item_id: string;
    owner_id: string;
    requester_id: string;
    status: LoanStatus;
    start_date: string;
    end_date: string;
    created_at: string;
    item: ItemPublic;
    owner: UserPublic;
    requester: UserPublic;
};

export type LoansPublic = {
    data: Array<LoanPublic>;
    count: number;
};

export type LoanStatus = 'pending' | 'accepted' | 'rejected' | 'active' | 'return_pending' | 'returned';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationPublic = {
    id: string;
    title: string;
    message: string;
    type: NotificationType;
    is_read: boolean;
    link: (string | null);
    created_at: string;
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
    unread_count: number;
};

export type NotificationType = 'info' | 'success' | 'warning' | 'error';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SearchResults = {
    users: Array<UserPublic>;
    items: Array<ItemPublic>;
    communities: Array<CommunityPublic>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    password: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
};

export type UserProfilePublic = {
    bio: (string | null);
    alias: (string | null);
    image_url: (string | null);
};

export type UserProfileUpdate = {
    bio?: (string | null);
    alias?: (string | null);
    interest_ids?: (Array<(string)> | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    public_id: string;
    id: string;
    communities?: Array<CommunityPublic>;
    community_role?: (CommunityMemberRole | null);
    community_status?: (CommunityMemberStatus | null);
    profile?: (UserProfilePublic | null);
    settings?: (UserSettingsSchema | null);
    interests?: Array<InterestPublic>;
    friendship_status?: (FriendshipStatus | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserSettingsSchema = {
    autocomplete_enabled?: boolean;
    theme_mode?: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CollectionsReadCollectionsData = {
    limit?: number;
    ownerId?: (string | null);
    skip?: number;
};

export type CollectionsReadCollectionsResponse = (CollectionsPublic);

export type CollectionsCreateCollectionData = {
    requestBody: CollectionCreate;
};

export type CollectionsCreateCollectionResponse = (CollectionPublic);

export type CollectionsReadCollectionData = {
    id: string;
};

export type CollectionsReadCollectionResponse = (CollectionPublic);

export type CollectionsUpdateCollectionData = {
    id: string;
    requestBody: CollectionUpdate;
};

export type CollectionsUpdateCollectionResponse = (CollectionPublic);

export type CollectionsDeleteCollectionData = {
    id: string;
};

export type CollectionsDeleteCollectionResponse = (Message);

export type CollectionsAddItemToCollectionData = {
    id: string;
    itemId: string;
};

export type CollectionsAddItemToCollectionResponse = (Message);

export type CollectionsRemoveItemFromCollectionData = {
    id: string;
    itemId: string;
};

export type CollectionsRemoveItemFromCollectionResponse = (Message);

export type CommunitiesReadCommunitiesData = {
    limit?: number;
    skip?: number;
};

export type CommunitiesReadCommunitiesResponse = (CommunitiesPublic);

export type CommunitiesCreateCommunityData = {
    requestBody: CommunityCreate;
};

export type CommunitiesCreateCommunityResponse = (CommunityPublic);

export type CommunitiesReadCommunityData = {
    id: string;
};

export type CommunitiesReadCommunityResponse = (CommunityPublic);

export type CommunitiesUpdateCommunityData = {
    id: string;
    requestBody: CommunityUpdate;
};

export type CommunitiesUpdateCommunityResponse = (CommunityPublic);

export type CommunitiesDeleteCommunityData = {
    id: string;
};

export type CommunitiesDeleteCommunityResponse = (Message);

export type CommunitiesJoinCommunityData = {
    id: string;
};

export type CommunitiesJoinCommunityResponse = (Message);

export type CommunitiesLeaveCommunityData = {
    id: string;
    userId?: (string | null);
};

export type CommunitiesLeaveCommunityResponse = (Message);

export type CommunitiesReadCommunityMembersData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type CommunitiesReadCommunityMembersResponse = (UsersPublic);

export type CommunitiesUpdateCommunityMemberRoleData = {
    id: string;
    requestBody: CommunityMemberUpdate;
    userId: string;
};

export type CommunitiesUpdateCommunityMemberRoleResponse = (UserPublic);

export type CommunitiesReadCommunityAnnouncementsData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type CommunitiesReadCommunityAnnouncementsResponse = (CommunityAnnouncementsPublic);

export type CommunitiesCreateCommunityAnnouncementData = {
    id: string;
    requestBody: CommunityAnnouncementCreate;
};

export type CommunitiesCreateCommunityAnnouncementResponse = (CommunityAnnouncementPublic);

export type CommunitiesReadCommunityMessagesData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type CommunitiesReadCommunityMessagesResponse = (CommunityMessagesPublic);

export type CommunitiesCreateCommunityMessageData = {
    id: string;
    requestBody: CommunityMessageCreate;
};

export type CommunitiesCreateCommunityMessageResponse = (CommunityMessagePublic);

export type FriendsSearchUserByIdData = {
    publicId: string;
};

export type FriendsSearchUserByIdResponse = (UserPublic);

export type FriendsReadFriendsData = {
    limit?: number;
    skip?: number;
};

export type FriendsReadFriendsResponse = (UsersPublic);

export type FriendsReadFriendRequestsData = {
    limit?: number;
    skip?: number;
};

export type FriendsReadFriendRequestsResponse = (UsersPublic);

export type FriendsReadSentFriendRequestsData = {
    limit?: number;
    skip?: number;
};

export type FriendsReadSentFriendRequestsResponse = (UsersPublic);

export type FriendsCreateFriendRequestData = {
    friendId: string;
};

export type FriendsCreateFriendRequestResponse = (Message);

export type FriendsAcceptFriendRequestData = {
    friendId: string;
};

export type FriendsAcceptFriendRequestResponse = (Message);

export type FriendsRemoveFriendData = {
    friendId: string;
};

export type FriendsRemoveFriendResponse = (Message);

export type InterestsReadInterestsData = {
    limit?: number;
    skip?: number;
};

export type InterestsReadInterestsResponse = (Array<InterestPublic>);

export type ItemsReadItemsData = {
    excludeCollections?: boolean;
    limit?: number;
    ownerId?: (string | null);
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    formData: Body_items_create_item;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    formData?: Body_items_update_item;
    id: string;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoansCreateLoanRequestData = {
    requestBody: LoanCreate;
};

export type LoansCreateLoanRequestResponse = (LoanPublic);

export type LoansReadIncomingLoanRequestsData = {
    limit?: number;
    skip?: number;
};

export type LoansReadIncomingLoanRequestsResponse = (LoansPublic);

export type LoansReadOutgoingLoanRequestsData = {
    limit?: number;
    skip?: number;
};

export type LoansReadOutgoingLoanRequestsResponse = (LoansPublic);

export type LoansRespondToLoanRequestData = {
    accept: boolean;
    id: string;
};

export type LoansRespondToLoanRequestResponse = (LoanPublic);

export type LoansRatifyLoanData = {
    id: string;
};

export type LoansRatifyLoanResponse = (LoanPublic);

export type LoansSignalReturnData = {
    id: string;
};

export type LoansSignalReturnResponse = (LoanPublic);

export type LoansReturnLoanData = {
    id: string;
};

export type LoansReturnLoanResponse = (LoanPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LoginLoginGoogleData = {
    requestBody: GoogleToken;
};

export type LoginLoginGoogleResponse = (Token);

export type NotificationsReadNotificationsData = {
    limit?: number;
    skip?: number;
};

export type NotificationsReadNotificationsResponse = (NotificationsPublic);

export type NotificationsMarkNotificationAsReadData = {
    id: string;
};

export type NotificationsMarkNotificationAsReadResponse = (NotificationPublic);

export type NotificationsMarkAllNotificationsAsReadResponse = (Message);

export type NotificationsDeleteNotificationData = {
    id: string;
};

export type NotificationsDeleteNotificationResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SearchSearchData = {
    limit?: number;
    q: string;
};

export type SearchSearchResponse = (SearchResults);

export type StorageUploadData = {
    formData: Body_storage_upload;
};

export type StorageUploadResponse = (Message);

export type StorageGetImageData = {
    filename: string;
    folder: string;
};

export type StorageGetImageResponse = (unknown);

export type StorageDeleteData = {
    filename: string;
    folder: string;
};

export type StorageDeleteResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersUpdateUserProfileData = {
    requestBody: UserProfileUpdate;
};

export type UsersUpdateUserProfileResponse = (UserPublic);

export type UsersUploadUserProfilePictureData = {
    formData: Body_users_upload_user_profile_picture;
};

export type UsersUploadUserProfilePictureResponse = (UserPublic);

export type UsersReadUserSettingsMeResponse = (UserSettingsSchema);

export type UsersUpdateUserSettingsData = {
    requestBody: UserSettingsSchema;
};

export type UsersUpdateUserSettingsResponse = (UserPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);