"""add notification table

Revision ID: 14901ae81ead
Revises: b860b0816a30
Create Date: 2026-01-21 19:36:21.554880

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14901ae81ead'
down_revision = 'b860b0816a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Fix for automatic cast
    op.alter_column('item', 'item_type',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('general', 'book', name='itemtype', create_type=False),
               existing_nullable=False,
               postgresql_using='item_type::itemtype')
    op.alter_column('item', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('item', 'item_type',
               existing_type=sa.Enum('general', 'book', name='itemtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('notification')
    op.execute("DROP TYPE itemtype")
    # ### end Alembic commands ###
