"""add item type and image url

Revision ID: 23af2928dd26
Revises: 83cac7a48e59
Create Date: 2026-01-18 17:16:11.804974

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '23af2928dd26'
down_revision = '83cac7a48e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
