"""Add has_set_password to User

Revision ID: 2b1d7123e5b5
Revises: 57123708a725
Create Date: 2026-01-25 22:13:31.244951

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2b1d7123e5b5'
down_revision = '57123708a725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('communityitem', 'added_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('communityitem', 'is_donation_pending',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('user', sa.Column('has_set_password', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_set_password')
    op.alter_column('communityitem', 'is_donation_pending',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('communityitem', 'added_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
