"""Add missing tables community friendship

Revision ID: 438fed9ccb14
Revises: b2c3d4e5f6g7
Create Date: 2026-01-17 15:48:12.099216

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '438fed9ccb14'
down_revision = 'b2c3d4e5f6g7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_name'), 'community', ['name'], unique=True)
    op.create_table('friendship',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('friend_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='friendshipstatus'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('communitymember',
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='communitymemberrole'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communitymember')
    op.drop_table('friendship')
    op.drop_index(op.f('ix_community_name'), table_name='community')
    op.drop_table('community')
    # ### end Alembic commands ###
