"""update community items pooling and donation

Revision ID: 57123708a725
Revises: 61000ef7ca2c
Create Date: 2026-01-25 19:19:59.411513

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '57123708a725'
down_revision = '61000ef7ca2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communityitem', sa.Column('added_by', sa.Uuid(), nullable=True))
    op.add_column('communityitem', sa.Column('is_donation_pending', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'communityitem', 'user', ['added_by'], ['id'], ondelete='CASCADE')
    op.add_column('item', sa.Column('community_owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'item', 'community', ['community_owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'community_owner_id')
    op.drop_constraint(None, 'communityitem', type_='foreignkey')
    op.drop_column('communityitem', 'is_donation_pending')
    op.drop_column('communityitem', 'added_by')
    # ### end Alembic commands ###
