"""add author and settings jsonb

Revision ID: 5ad46be3404a
Revises: 14901ae81ead
Create Date: 2026-01-22 05:02:16.363786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5ad46be3404a'
down_revision = '14901ae81ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settings', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('item', sa.Column('author', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'author')
    op.drop_column('user', 'settings')
    # ### end Alembic commands ###
