"""add pending_extension_date to loan

Revision ID: 5f44452a606c
Revises: e565e3765c6b
Create Date: 2026-01-26 05:09:58.503920

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5f44452a606c'
down_revision = 'e565e3765c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('pending_extension_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'pending_extension_date')
    # ### end Alembic commands ###
