"""add community items and update loans

Revision ID: 61000ef7ca2c
Revises: c7d072f98632
Create Date: 2026-01-25 18:51:49.022731

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '61000ef7ca2c'
down_revision = 'c7d072f98632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communityitem',
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_id', 'item_id')
    )
    op.add_column('loan', sa.Column('community_id', sa.Uuid(), nullable=True))
    op.alter_column('loan', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'loan', 'community', ['community_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.alter_column('loan', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('loan', 'community_id')
    op.drop_table('communityitem')
    # ### end Alembic commands ###
