"""Add profile settings interests

Revision ID: 83cac7a48e59
Revises: 539fed9ccb15
Create Date: 2026-01-18 14:50:22.201193

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '83cac7a48e59'
down_revision = '539fed9ccb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
