"""add notifications_enabled to communitymember

Revision ID: c7d072f98632
Revises: c519772f923d
Create Date: 2026-01-25 18:01:26.362555

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c7d072f98632'
down_revision = 'c519772f923d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communitymember', sa.Column('notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communitymember', 'notifications_enabled')
    # ### end Alembic commands ###
