"""add cascade delete to community created_by

Revision ID: e565e3765c6b
Revises: 2b1d7123e5b5
Create Date: 2026-01-26 04:53:52.646430

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e565e3765c6b'
down_revision = '2b1d7123e5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('community_created_by_fkey', 'community', type_='foreignkey')
    op.create_foreign_key(None, 'community', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'community', type_='foreignkey')
    op.create_foreign_key('community_created_by_fkey', 'community', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###
