"""Add missing tables and relationships

Revision ID: edb7880990de
Revises: 23af2928dd26
Create Date: 2026-01-18 18:03:03.826722

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'edb7880990de'
down_revision = '23af2928dd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create itemtype enum
    sa.Enum('general', 'book', name='itemtype').create(op.get_bind())
    
    op.create_table('interest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_name'), 'interest', ['name'], unique=True)
    op.create_table('userinterest',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interest_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    op.create_table('useritem',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.create_table('userprofile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('usersettings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('communityinterest',
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('interest_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interest_id'], ['interest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('community_id', 'interest_id')
    )
    op.add_column('item', sa.Column('item_type', sa.Enum('general', 'book', name='itemtype'), nullable=False, server_default='general'))
    op.add_column('item', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    op.add_column('item', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.add_column('item', sa.Column('count', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_item_title'), 'item', ['title'], unique=False)
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    # Note: the foreign key name might be different depending on when it was created, 
    # but the autogenerated code had 'item_owner_id_fkey'
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_item_title'), table_name='item')
    op.drop_column('item', 'count')
    op.drop_column('item', 'extra_data')
    op.drop_column('item', 'image_url')
    op.drop_column('item', 'item_type')
    op.drop_table('communityinterest')
    op.drop_table('usersettings')
    op.drop_table('userprofile')
    op.drop_table('useritem')
    op.drop_table('userinterest')
    op.drop_index(op.f('ix_interest_name'), table_name='interest')
    op.drop_table('interest')
    
    # Drop itemtype enum
    sa.Enum('general', 'book', name='itemtype').drop(op.get_bind())
    # ### end Alembic commands ###
