"""Add RETURN_PENDING to loanstatus

Revision ID: ff69aa375024
Revises: 1d1c3169f4de
Create Date: 2026-01-23 21:50:18.625284

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ff69aa375024'
down_revision = '1d1c3169f4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("COMMIT") # Not recommended, better to use non-transactional context
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE loanstatus ADD VALUE 'RETURN_PENDING'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Postgres doesn't easily support removing enum values.
    pass
    # ### end Alembic commands ###
