export const SESSION_INACTIVITY_TIMEOUT = 30 * 60 * 1000 // 30 minutes

export const BOOK_CLASSIFICATION: Record<string, string[]> = {
  Fiction: [
    "Fantasy",
    "Science Fiction (Sci-Fi)",
    "Mystery & Crime",
    "Thriller & Suspense",
    "Romance",
    "Historical Fiction",
    "Horror",
    "Literary Fiction",
    "Adventure",
    "Dystopian",
    "Graphic Novels & Comics",
    "Westerns",
  ],
  "Non-Fiction": [
    "Biography & Memoir",
    "Self-Help & Personal Development",
    "History",
    "Science & Nature",
    "Business & Money",
    "Health & Fitness",
    "Travel",
    "Cookbooks & Food",
    "Religion & Spirituality",
    "Philosophy",
    "Politics & Social Sciences",
    "True Crime",
    "Art & Photography",
    "Essays & Criticism",
  ],
  "Children's & Young Adult": [
    "Board Books",
    "Picture Books",
    "Early Readers",
    "Middle Grade",
    "Young Adult (YA)",
  ],
  "Academic & Professional": [
    "Textbooks",
    "Reference (Dictionaries, Encyclopedias)",
    "Medical",
    "Law",
    "Computer Science & Technology",
    "Engineering",
  ],
}
